theme = "reveal-hugo"
disableKinds = ["taxonomy", "term", "sitemap", "RSS"]
baseURL = "https://gsoc-cupy-talk.khushi-411.github.io/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "custom-theme.scss"
custom_theme_compile = true
# theme = "white"
highlight_theme = "monokai-sublime"
width = 1500
height = 900
slide_number = true
transition_speed = "fast"
